[package]
name = "miner-rust"
version = "0.1.0"
license = "ISC"
edition = "2021"

[dependencies]
futures = "0.3"
log = "^0.4"
base64 = "^0.13"
sodalite = "^0.4"
psrt = "^0.1"
tokio = "^1.15"
tokio-util = "^0.6"
parity-tokio-ipc = "^0.9"
serde = "^1.0"
serde_json = "^1.0"